local Classes = {}

Classes["Archer"] = {
	HP = 2100,
	MP = 250,
	ATT = 75,
	DEF = 25,
	SPD = 55,
	DEX = 50,
	VIT = 40,
	WIS = 50,
}

Classes["Huntress"] = {
	HP = 2100,
	MP = 300,
	ATT = 65,
	DEF = 25,
	SPD = 50,
	DEX = 60,
	VIT = 40,
	WIS = 50,
}

Classes["Bard"] = {
	HP = 1900,
	MP = 380,
	ATT = 55,
	DEF = 25,
	SPD = 55,
	DEX = 70,
	VIT = 45,
	WIS = 75,
}

Classes["Rogue"] = {
	HP = 2200,
	MP = 252,
	ATT = 50,
	DEF = 25,
	SPD = 75,
	DEX = 75,
	VIT = 40,
	WIS = 50,
}

Classes["Assassin"] = {
	HP = 2200,
	MP = 300,
	ATT = 65,
	DEF = 25,
	SPD = 65,
	DEX = 75,
	VIT = 40,
	WIS = 60,
}

Classes["Wizard"] = {
	HP = 1900,
	MP = 380,
	ATT = 75,
	DEF = 25,
	SPD = 50,
	DEX = 75,
	VIT = 40,
	WIS = 60,
}

Classes["Necromancer"] = {
	HP = 1900,
	MP = 380,
	ATT = 75,
	DEF = 25,
	SPD = 50,
	DEX = 60,
	VIT = 40,
	WIS = 75,
}

Classes["Mystic"] = {
	HP = 1900,
	MP = 380,
	ATT = 65,
	DEF = 25,
	SPD = 60,
	DEX = 65,
	VIT = 40,
	WIS = 75,
}

Classes["Priest"] = {
	HP = 1900,
	MP = 380,
	ATT = 50,
	DEF = 25,
	SPD = 55,
	DEX = 55,
	VIT = 40,
	WIS = 75,
}

Classes["Sorcerer"] = {
	HP = 1900,
	MP = 380,
	ATT = 75,
	DEF = 25,
	SPD = 60,
	DEX = 65,
	VIT = 75,
	WIS = 60,
}

Classes["Warrior"] = {
	HP = 2700,
	MP = 250,
	ATT = 75,
	DEF = 25,
	SPD = 40,
	DEX = 50,
	VIT = 75,
	WIS = 50,
}

Classes["Knight"] = {
	HP = 2700,
	MP = 250,
	ATT = 50,
	DEF = 40,
	SPD = 40,
	DEX = 50,
	VIT = 75,
	WIS = 50,
}

Classes["Paladin"] = {
	HP = 2700,
	MP = 250,
	ATT = 50,
	DEF = 30,
	SPD = 45,
	DEX = 55,
	VIT = 60,
	WIS = 75,
}

Classes["Ninja"] = {
	HP = 2200,
	MP = 250,
	ATT = 50,
	DEF = 25,
	SPD = 60,
	DEX = 70,
	VIT = 60,
	WIS = 70,
}

Classes["Samurai"] = {
	HP = 2200,
	MP = 250,
	ATT = 75,
	DEF = 30,
	SPD = 50,
	DEX = 50,
	VIT = 60,
	WIS = 50,
}

Classes["Kensei"] = {
	HP = 2200,
	MP = 250,
	ATT = 65,
	DEF = 25,
	SPD = 60,
	DEX = 50,
	VIT = 60,
	WIS = 50,
}

return Classes
