local Descricao = {
	Dano = "Damage",
	VelocidadeProjetil = "Velocidade",
	DistanciaMaximaProjetil = "Alcance",
	CustoDeHabilidade = "MP Cost",
	DistanciaMaximaDaHabilidade = "Distancia maxima",
}

Descricao.TipoDeEquipamento = {
	Archer = "quiver",
	Rogue = "cloak",
	Warrior = "helm",
	Wizard = "spell",
	Priest = "tome",
	Knight = "shield",
	Paladin = "seal",
	Assassin = "Poison",
	Necromancer = "skull",
	Huntress = "trap",
	Mystic = "orb",
	Trickster = "prism",
	Sorcerer = "scepters",
	Ninja = "star",
	Samurai = "wakizashi",
	Bard = "lute",
	Summoner = "mace",
	Kensei = "sheath",
}

return Descricao
