local StarterGui = game:GetService("StarterGui")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local LeatherBoard = StarterGui:WaitForChild("LeatherBoard")
local Menu = StarterGui:WaitForChild("Menu")
local HUD = StarterGui:WaitForChild("HUD")
local DeadScreen = StarterGui:WaitForChild("DeadScreen")

LeatherBoard.Parent = ReplicatedStorage
Menu.Parent = ReplicatedStorage
HUD.Parent = ReplicatedStorage
DeadScreen.Parent = ReplicatedStorage
